ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER EMPRESA
IDENTIFIED BY EMPRESA;

ALTER USER EMPRESA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO EMPRESA;

CREATE TABLESPACE tony_tbs
 DATAFILE 'example_tbs.dbf' SIZE 100M
 AUTOEXTEND ON
 NEXT 10M MAXSIZE 500M;
 
ALTER TABLESPACE tony_tbs OFFLINE;

ALTER DATABASE RENAME FILE 'C:\APP\IFSP\PRODUCT\21C\DBHOMEXE\
DATABASE\EXAMPLE_TBS.DBF'
TO 'C:\APP\IFSP\PRODUCT\21C\DBHOMEXE\DATABASE\TONY_TBS.DBF';

ALTER TABLESPACE tony_tbs ONLINE;

SELECT FILE_NAME FROM DBA_DATA_FILES WHERE TABLESPACE_NAME =
'tony_tbs';

ALTER TABLESPACE EXAMPLE_TBS RENAME TO TONY_TBS;

DROP TABLESPACE TONY_TBS INCLUDING CONTENTS
AND DATAFILES;

ALTER TABLESPACE TONY_TBS
 ADD DATAFILE 'vinicius_tbs_02.dbf' SIZE 100M
 AUTOEXTEND ON
 NEXT 10M MAXSIZE 500M;
 
CREATE OR REPLACE DIRECTORY teste_dump AS 'C:\Users\IFSP\Downloads\DUMPSIL';

GRANT READ, WRITE ON DIRECTORY teste_dump TO EMPRESA;

create or replace directory Dumps as 'C:/Temp/';

